use_frameworks!

platform :ios, '9.0'

target 'standardUI_Example' do
  pod 'StandardUI', :path => '../'

  target 'standardUI_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 9.2.1'
  end
end
